### ISSUE TITLE
想要查看代码，但是出现Error Retrieve Submission的报错

### ISSUE THREAD

**Issue by bakebakebakebake** [dianhsu/cf-code#2]
rt，点开代码显示这个捏🙂
![image](https://github.com/dianhsu/cf-code/assets/119475415/aecc083c-f1e9-4a76-8adf-c6f5ca609dd6)

**Comment by dianhsu** [comment]
你好，如果查看代码的时候，刚好有比赛，然后无法查看code是正常现象。因为Codeforces在比赛的时候会启用Cloudflare，那样的话，就没办法去爬代码了。

**Comment by bakebakebakebake** [comment]
> 你好，如果查看代码的时候，刚好有比赛，然后无法查看code是正常现象。因为Codeforces在比赛的时候会启用Cloudflare，那样的话，就没办法去爬代码了。

你好，如果是邀请进入的比赛是看不了代码是吗？

**Comment by dianhsu** [comment]
因为我的账号没有访问的权限，所以看不到🤣

bakebakebakebake ***@***.***>于2024年5月31日 周五13:40写道：
