### ISSUE TITLE
在非比赛期间也出现Error Retrieve Submission，一周内测试了两次都是如此

### ISSUE THREAD

**Issue by my-mathmaster** [dianhsu/cf-code#3]
rt

**Comment by dianhsu** [comment]
Ok, I will check it.

**Comment by Rayano534** [comment]
I have the same problem on literally every submission I'm trying to open, when will it be fixed?
Thank you for your effort Dianhsu.

**Comment by dianhsu** [comment]
Codeforces enable Cloudflare security check, it will prevent automatic software crawl data from Codeforces. Currently, I have no idea to bypass Cloudflare security check.

**Comment by Rayano534** [comment]
I see, is there any other way to view the submissions tho?
